dbConfig:
  host: localhost
  port: 27017
  dbName: sms

googleApiKey: AIzaSyCp0VnNyEznPykPPhzA660Y1ZGdf0WGUxI

test:
  dbConfig:
    dbName: sms-login-test

  server:
    url: http://login.sharemyscreen.local
    port: 3000

server:
  port: 3000
